version: "2"
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=dodol123
    volumes: 
      - mongo-data:/data/db
  mongo_express:
    image: "mongo-express"
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dodol123
    ports:
      - 8081:8081

volumes:
  mongo-data: